executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/leoalmeidasant/task-orchestration-platform.git
    branch: main
    rev: HEAD
    depth: 1
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags-config/"
    wait: 60
    containerName: git-sync
    uid: 65533