dag_name: task_orchestration
schedule_interval: '@daily'
owner_email:
  - teste@test.com
owner_name: test
depends_on_past: false 
is_paused_upon_creation: false
files:
  - file_name: consumer.csv.gz
    file_uri: https://ifood-data-architect-test-source.s3-sa-east-1.amazonaws.com/consumer.csv.gz
    s3_output_bucket: s3://path-to-bucket
    compression_type: gzip
